### ISSUE TITLE
Suggestion: Alternate music

### ISSUE THREAD

**Issue by nchutchind** [m3rt32/UnityElevatorCompiler#2]
Kevin MacLeod's "Local Forecast - Elevator" has a great elevator muzak vibe to it, is royalty-free, and is just over 3 minutes long. It could be a useful alternative to the short wav file currently in use.

https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1300012

**Comment by mert-dev-acc** [comment]
I quite liked it ! New update will bring editor player, having multiple clips and shuffling. You may track it in develop branch.

I'll add this to default music presets.
Thank you!

**Comment by mert-dev-acc** [comment]
Done! New update will be shipped shortly.
