### ISSUE TITLE
Pre 2018 versions of unity don't have lightmapping.started callback

### ISSUE THREAD

**Issue by alekso56** [m3rt32/UnityElevatorCompiler#4]
Callback doesn't exist for older versions of unity.

**Comment by mert-dev-acc** [comment]
Good point! I'll look into it.

**Comment by mert-dev-acc** [comment]
Sorry it took so long but I believe issue has fixed with the [Latest commit](https://github.com/m3rt32/UnityElevatorCompiler/commit/e670a089476b75c623a1f7bea2231791fcbdc74a)
